### ISSUE TITLE
Setup circleci continuous CICID

### ISSUE THREAD

**Issue by reecemillsom** [reecemillsom/http-request-client#13]
* Free circle ci integration for open source projects.
* Means having assurance that the builds are passing both locally and in another environment.

**Comment by reecemillsom** [comment]
Decided to go with Travis CI, as it makes for an easy intergration for having labels for coverage and build on read me with codecov

**Comment by digitalfu** [comment]
Is this complete?

**Comment by reecemillsom** [comment]
I decided to go with Travis CI, because I have more familiarity with its setup. I wouldn't say complete but when I push to master at least it will run tests and codecov for my README labels
